### ISSUE TITLE
Text: If version is filled, Variant property does not work

### ISSUE THREAD

**Issue by pavol-marko** [axa-ch/patterns-library#1979]
When Version is filled in createAxaText, the Variant property does not Work for Text.

## Expected Behavior
Variant property of Text should work independently of Version

## Steps to Reproduce
1. Create AxaText with version

const version = "esales";
const AxaTextReact = createAXAText(createElement, version);
export const SomeText = () => <AxaTextReact variant="bold">Text</AxaTextReact>

Der text ist nicht bold wie er sein sollte
Wenn mann aber die Version entfernt funktioniert das wie erwartet

## Context (Environment)
We version all components of PL due to possible conflicts with other pods. In this case it is not possible

**Comment by markus-walther** [comment]
This is clearly a bug and could be replicated. I get a console error `cssAsString.split is not a function
    at HTMLElement.inlineStyles (inline-styles.js:53)` that points to what's going on here.

Such errors are very helpful, so I would suggest to always attach them to a bug report, if available.
